import { createClient } from "@supabase/supabase-js"
import { sendEmail } from "../../lib/sendEmail"
import Groq from "groq-sdk"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
)

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY })

export async function GET(request) {
  const authHeader = request.headers.get("authorization")
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return Response.json({ error: "Unauthorized" }, { status: 401 })
  }

  try {
    const now = new Date()
    const thirtyMinutesAgo = new Date(now.getTime() - 30 * 60000)
    const ninetyMinutesAgo = new Date(now.getTime() - 90 * 60000)

    const { data: meetings } = await supabase
      .from("meetings")
      .select("*")
      .eq("status", "brief_sent")
      .gte("scheduled_at", ninetyMinutesAgo.toISOString())
      .lte("scheduled_at", thirtyMinutesAgo.toISOString())

    if (!meetings || meetings.length === 0) {
      return Response.json({ message: "No completed meetings", processed: 0 })
    }

    let processed = 0

    for (const meeting of meetings) {
      const { data: user } = await supabase
        .from("users")
        .select("email, name, timezone")
        .eq("id", meeting.user_id)
        .single()

      if (!user) continue

      const notesResult = await groq.chat.completions.create({
        messages: [{
          role: "user",
          content: `Generate professional meeting notes template:
Meeting: ${meeting.title}
Attendee: ${meeting.attendee_name}
Context: ${meeting.brief}

Format:
MEETING NOTES
Date: ${new Date().toLocaleDateString()}
With: ${meeting.attendee_name}

SUMMARY:
[2-3 sentences]

KEY POINTS:
• [point 1]
• [point 2]
• [point 3]

ACTION ITEMS:
• [action 1]
• [action 2]

NEXT STEPS:
[what happens next]

Note: Edit these AI-generated notes to match your actual discussion.`
        }],
        model: "llama-3.1-8b-instant",
        max_tokens: 400
      })

      const notes = notesResult.choices[0].message.content
      const meetingDate = new Date(meeting.scheduled_at).toLocaleDateString("en-US", {
        weekday: "long", month: "long", day: "numeric",
        timeZone: user.timezone || "America/New_York"
      })

      await sendEmail({
        to: user.email,
        subject: `Meeting notes: ${meeting.title} — ${meetingDate}`,
        body: `
          <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto">
            <h2 style="color:#4F46E5">Your meeting notes are ready</h2>
            <p style="color:#6B7280">Meeting with ${meeting.attendee_name} on ${meetingDate}</p>
            <div style="background:#F9FAFB;border:1px solid #E5E7EB;border-radius:8px;padding:20px;margin:16px 0">
              <pre style="white-space:pre-wrap;font-family:Arial,sans-serif;line-height:1.7;color:#374151;margin:0">${notes}</pre>
            </div>
            <p style="color:#EF4444;font-size:13px">These are AI-generated template notes. Please edit to match your actual discussion.</p>
            <p style="color:#9CA3AF;font-size:12px">Generated by MeetingAI</p>
          </div>
        `
      })

      await sendEmail({
        to: meeting.attendee_email,
        subject: `Thank you for meeting: ${meeting.title}`,
        body: `
          <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto">
            <h2 style="color:#4F46E5">Thank you for your time!</h2>
            <p>Hi ${meeting.attendee_name},</p>
            <p>Thank you for taking the time to meet today. I really appreciated our conversation.</p>
            <p>I will follow up with any relevant details we discussed shortly.</p>
            <p>Looking forward to our next steps!</p>
            <p style="color:#9CA3AF;font-size:12px">Sent by MeetingAI</p>
          </div>
        `
      })

      await supabase
        .from("meetings")
        .update({
          status: "completed",
          brief: meeting.brief + "\n\nMEETING NOTES:\n" + notes
        })
        .eq("id", meeting.id)

      processed++
    }

    return Response.json({ success: true, processed })

  } catch (error) {
    console.error("Auto notes error:", error)
    return Response.json({ error: error.message }, { status: 500 })
  }
}