import { createClient } from "@supabase/supabase-js"
import { sendEmail } from "../../lib/sendEmail"
import Groq from "groq-sdk"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
)

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY })

export async function GET() {
  try {
    const now = new Date()
    const oneHourFromNow = new Date(now.getTime() + 60 * 60000)
    const twoHoursFromNow = new Date(now.getTime() + 120 * 60000)

    // Find all approved meetings starting in the next 1-2 hours
    const { data: upcomingMeetings } = await supabase
      .from("meetings")
      .select("*, users(email, name)")
      .eq("status", "approved")
      .gte("scheduled_at", oneHourFromNow.toISOString())
      .lte("scheduled_at", twoHoursFromNow.toISOString())

    if (!upcomingMeetings || upcomingMeetings.length === 0) {
      return Response.json({ message: "No upcoming meetings to brief" })
    }

    for (const meeting of upcomingMeetings) {
      // Ask AI to generate a preparation brief
      const aiResult = await groq.chat.completions.create({
        messages: [{
          role: "user",
          content: `You are a professional assistant. Generate a short, helpful pre-meeting brief for this meeting:

Meeting title: ${meeting.title}
With: ${meeting.attendee_name}
Original context: ${meeting.brief}

Write a brief in this format:
WHO: one sentence about who this person likely is based on context
PURPOSE: what this meeting is likely about
PREPARE: 2-3 bullet points of what to prepare or think about
TIPS: one helpful tip for making this meeting successful

Keep it short, professional, and genuinely useful.`
        }],
        model: "llama-3.1-8b-instant"
      })

      const briefContent = aiResult.choices[0].message.content

      // Get the owner's email from users table
      const { data: user } = await supabase
        .from("users")
        .select("email, name")
        .eq("id", meeting.user_id)
        .single()

      const meetingTime = new Date(meeting.scheduled_at).toLocaleTimeString("en-US", {
        hour: "2-digit",
        minute: "2-digit"
      })

      // Send brief to owner
      await sendEmail({
        to: user.email,
        subject: `Meeting Brief: ${meeting.title} at ${meetingTime}`,
        body: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #4F46E5;">Your Meeting Starts in 1 Hour</h2>
            <div style="background: #EEF2FF; padding: 12px 16px; border-radius: 8px; margin-bottom: 16px;">
              <p style="margin: 0;"><strong>${meeting.title}</strong></p>
              <p style="margin: 4px 0 0; color: #6B7280;">
                with ${meeting.attendee_name} at ${meetingTime}
              </p>
            </div>
            <div style="white-space: pre-wrap; line-height: 1.6; color: #374151;">
              ${briefContent}
            </div>
            <p style="color: #6B7280; font-size: 12px; margin-top: 24px;">
              This brief was automatically generated by MeetingAI
            </p>
          </div>
        `
      })

      // Mark brief as sent so we don't send it twice
      await supabase
        .from("meetings")
        .update({ status: "brief_sent" })
        .eq("id", meeting.id)
    }

    return Response.json({ 
      success: true, 
      briefsSent: upcomingMeetings.length 
    })

  } catch (error) {
    console.error("Send briefs error:", error)
    return Response.json({ error: error.message }, { status: 500 })
  }
}